name: Build MechWild QMK firmware
on: [push, workflow_dispatch]
# NOTE: workflow_dispatch is only available for the default branch, SIGH ("https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually")

permissions: {}

jobs:
  build:
    if: github.event.sender.login == 'kylemccreery'
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      # TODO: break the matrix construction out into its own job, zmk-style?
      matrix:
        keyboard: [obe/f401]
        keymap: [default, via, vial]

    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set output variables for later job steps
        id: vars
        # Thanks, StackOverflow: https://stackoverflow.com/a/12704727
        run: |
          echo cache-mw-qmk-hash=$(git -c 'versionsort.suffix=' ls-remote --exit-code --sort='-version:refname' --tags --refs https://github.com/MechWild/qmk_firmware.git experimental_firmware '*.*.*' | grep -P 'refs/tags/\d+\.\d+\.\d+' | head -n1 | cut -f1) >> $GITHUB_OUTPUT
          echo cache-qmk-hash=$(git -c 'versionsort.suffix=' ls-remote --exit-code --sort='-version:refname' --tags --refs https://github.com/qmk/qmk_firmware.git master '*.*.*' | grep -P 'refs/tags/\d+\.\d+\.\d+' | head -n1 | cut -f1) >> $GITHUB_OUTPUT
          echo keyboard-filename=$(echo ${{ matrix.keyboard }} | tr '/' '_') >> $GITHUB_OUTPUT

      - name: Cache repos
        id: cache-repos
        uses: actions/cache@v3
        with:
          # TODO: Is a better key possible without cloning the repo? Vial doesn't tag...
          key: ${{ steps.vars.outputs.cache-qmk-hash }}
          path: |
            qmk_firmware
            vial-qmk

      - name: Checkout QMK
        if: ${{ ! steps.cache-repos.outputs.cache-hit || matrix.keymap != 'vial' }}
        uses: actions/checkout@v3
        with:
          repository: mechwild/qmk_firmware
          ref: experimental_firmware
          submodules: recursive
          path: qmk_firmware
          
      - name: Update from QMK master to MW fork
        if: ${{ steps.vars.outputs.cache-mw-qmk-hash != steps.vars.outputs.cache-qmk-hash }}
        id: mw-qmk-update
        env: 
          UPSTREAM: https://github.com/MechWild/qmk_firmware.git
        run: |
          ls -lisa
          cd qmk_firmware
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote add upstream $UPSTREAM
          echo "Fetching upstream master"
          git fetch upstream master
          echo "Pulling upstream master"
          git pull --no-edit upstream master --allow-unrelated-histories
          echo "Fetching upstream tags"
          git fetch --tags --all
          echo "pulling tags"
          git pull --tags --all
          cd ..

      - name: Create PR with QMK version updates
        if: ${{ steps.vars.outputs.cache-mw-qmk-hash != steps.vars.outputs.cache-qmk-hash }}
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Automatically creating pull request to update to new QMK
          branch: experimental_firmware

      - name: Checkout Vial
        if: ${{ ! steps.cache-repos.outputs.cache-hit || matrix.keymap == 'vial' }}
        uses: actions/checkout@v3
        with:
          repository: mechwild/vial-qmk
          ref: experimental_firmware
          submodules: recursive
          path: vial-qmk

      - name: Change branches in QMK and VIAL git
        run: |
          git --git-dir=qmk_firmware/.git --work-tree=qmk_firmware checkout experimental_firmware
          git --git-dir=vial-qmk/.git --work-tree=vial-qmk checkout experimental_firmware

      - name: Build QMK firmware
      # Seems unnecessary to specify on whether it is vial keymap or not, just remove vial from keymap array and hardcode it in the vial build command
        if: ${{ matrix.keymap != 'vial' }}
        run: make -C qmk_firmware mechwild/${{ matrix.keyboard }}:${{ matrix.keymap }} -j$(nproc)

      - name: Build Vial firmware
        if: ${{ matrix.keymap == 'vial' }}
        run: make -C vial-qmk make mechwild/${{ matrix.keyboard }}:${{ matrix.keymap }} -j$(nproc)

      - name: Move keymaps
        # If the keymaps aren't (re)moved, they'll end up archived with the repos!
        run: |
          mkdir ${{ steps.vars.outputs.keyboard-filename }} && mv */mechwild_${{ steps.vars.outputs.keyboard-filename }}_${{ matrix.keymap }}.* ${{ steps.vars.outputs.keyboard-filename }}
      - name: Zip firmware
        uses: actions/upload-artifact@v3
        continue-on-error: false
        with:
          name: mechwild-keymaps
          path: |
            */mechwild_${{ steps.vars.outputs.keyboard-filename }}_${{ matrix.keymap }}.hex
            */mechwild_${{ steps.vars.outputs.keyboard-filename }}_${{ matrix.keymap }}.bin
            */mechwild_${{ steps.vars.outputs.keyboard-filename }}_${{ matrix.keymap }}.uf2
      - name: Clean .build folders
        run: |
          [ -d qmk_firmware ] && make -C qmk_firmware clean
          [ -d vial-qmk ] && make -C vial-qmk clean